import streamlit as st

st.subheader("Citation Guidelines")
st.markdown("<p>While we encourage you to use these resources for your research and commercial purposes, we want to ensure that our content is given proper citation in all cases where it is used.</p>", unsafe_allow_html=True)
st.subheader("General Citation")
st.markdown("<p>If you cite or display any content, or reference this website, in any format, written or otherwise, including print or web publications, presentations, grant applications, websites, other online applications such as blogs, or other works, you must include a reference to our website: <a href = 'https://spatial-gbm.streamlit.app/' >https://spatial-gbm.streamlit.app/</a></p>", unsafe_allow_html=True)
st.subheader("Reference")
st.markdown("<p> Linan Zhang, April Sagan, Bin Qin, Baoli Hu, Hatice Ulku Osmanbeyoglu. <strong>STAN, a computational framework for inferring spatially informed transcription factor activity across cellular contexts</strong>: bioRxiv 2024.06.26.600782; doi: <a href = 'https://www.biorxiv.org/content/10.1101/2024.06.26.600782v2'>https://doi.org/10.1101/2024.06.26.600782</a></p>", unsafe_allow_html=True)
st.markdown("<p> Kazumasa Kanemaru, James Cranley, Daniele Muraro, Antonio M. A. Miranda, Siew Yen Ho, Anna Wilbrey-Clark, Jan Patrick Pett, Krzysztof Polanski, Laura Richardson, Monika Litvinukova, Natsuhiko Kumasaka, Yue Qin, Zuzanna Jablonska, Claudia I. Semprich, Lukas Mach, Monika Dabrowska, Nathan Richoz, Liam Bolt, Lira Mamanova, Rakeshlal Kapuge, Sam N. Barnett, Shani Perera, Carlos Talavera-López, Ilaria Mulas, Krishnaa T. Mahbubani, Liz Tuck, Lu Wang, Margaret M. Huang, Martin Prete, Sophie Pritchard, John Dark, Kourosh Saeb-Parsy, Minal Patel, Menna R. Clatworthy, Norbert Hübner, Rasheda A. Chowdhury, Michela Noseda & Sarah A. Teichmann. <strong>Spatially resolved multiomics of human cardiac niches</strong>: Nature volume 619, pages801–810 (2023) <a href = 'https://www.nature.com/articles/s41586-023-06311-1'>https://www.nature.com/articles/s41586-023-06311-1</a></p>", unsafe_allow_html=True)
